### PR TITLE
Fix internal deprecated api use

### LINKED ISSUE #336: Fix internal deprecated API use

### PR DESCRIPTION
**Pull request by rainman110**
## Summary

  This PR migrates IntelliGraph node widget customization away from the deprecated `Node::registerWidgetFactory(...)` API to the current `NodeUI`-based approach.

  The refactoring keeps runtime behavior equivalent while removing deprecated API usage node-by-node.

  ## What Changed

  ### Deprecated widget migration
  - Replaced legacy `registerWidgetFactory(...)` usage with dedicated `NodeUI` subclasses overriding `NodeUI::centralWidgetFactory(...)`.
  - Registered the new UI classes in `GtIntelliGraphModule::uiItems()`.

  ### Node/UI state synchronization improvements
  - Moved widget-specific logic into `NodeUI` classes.
  - Added explicit node state APIs + signals where needed (instead of sharing widget state implicitly).

  ### Code quality / maintenance
  - Reduced duplication between `IntInputNode` / `DoubleInputNode` and their UI classes via shared helpers.
  - Added comments/documentation in migrated UI code where behavior is non-obvious.

  ## Migrated Nodes

  Includes migration of the remaining deprecated widget-factory nodes, including input nodes and several exec/helper nodes e.g.
 - number math
 - directory source
 - object sink
 - string builder/selection
 - object/string/int/double input
 - sleepy
 - find direct child
 - generic calculator exec

  ## Verification

  - Manually validated migrated node UIs during migration

### CODE REVIEW

**Review by jensschmeink — APPROVED** [review]
@rainman110 I had a look at the code. I have only 2 incremental annotations. I also used the code in my master build to check several existing (also larger) intelli graphs and I did not see any problems.

**Comment by jensschmeink** [comment]
@rainman110 There is one more question: my IDE shows this warning: 
...\src\intelli\gui\ui\node\existingdirectorysourcenodeui.cpp(55): warning C4573: Fr die Syntax von "QObject::connect" muss der Compiler "this" erfassen, der aktuelle Standarderfassungsmodus l„sst dies jedoch nicht zu.

**Comment by mariusalexander** [comment]
Peek a boo!

@rainman110  Wow you have been very busy, many thanks! That sure was time consuming...

@jensschmeink 

> warning C4573: F�r die Syntax von "QObject::connect" muss der Compiler "this" erfassen, der aktuelle Standarderfassungsmodus l„sst dies jedoch nicht zu.

Hi, in my opinion this is a bug of the code analyzer/the IDE. I had a similar problem once. In your example we are calling the static function `QObject::connect`. However, `QObject` also implements non-static `(this->)connect` overloads. Apparently the analyzer (mistakenly) thinks we are calling the non-static member function and thus thinks we have to capture `this` for the lambda. I do not know a workaround or a way to silence this warning.

One could change the capture clause of the lambda to `[this](){....}` but doing so would be inaccurate and in fact I think another warning would pop up which states that `this` is not used :D

**Comment by rainman110** [comment]
> Peek a boo!
> 
> @rainman110 Wow you have been very busy, many thanks! That sure was time consuming...

I had some help, a little coding monkey 😆

File: src/intelli/node/sleepy.cpp [hunk 1]
```diff
@@ -30,28 +30,13 @@ SleepyNode::SleepyNode() :
...
-                gt::gui::icon::check().pixmap(20, 20));
-        };
-        connect(this, &SleepyNode::timePassed, w.get(), update);
-        connect(this, &Node::inputDataRecieved, w.get(), reset);
-
-        reset();
-
-        return w;
-    });
+    // Widget creation moved to NodeUI.
```
Comment (rainman110) [inline src/intelli/node/sleepy.cpp]:
```suggestion
```

**Comment by rainman110** [comment]
@jensschmeink can we merge it?

**Comment by jensschmeink** [comment]
> @jensschmeink can we merge it?

Yes, I see no problems
